//------------------------------------------------------------------------------
// <auto-generated>
//     ? ??? ??? ???? ???????.
//     ??? ??:4.0.30319.42000
//
//     ?? ??? ???? ??? ??? ??? ? ???, ??? ?? ????
//     ??? ?? ??? ?????.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TarkovQuestScanner.Properties {
    using System;
    
    
    /// <summary>
    ///   ???? ??? ?? ?? ?? ??? ??? ??? ??????.
    /// </summary>
    // ? ???? ResGen ?? Visual Studio? ?? ??? ?? StronglyTypedResourceBuilder
    // ????? ???? ???????.
    // ??? ????? ????? .ResX ??? ??? ?? /str ??? ???? ResGen?
    // ?? ????? VS ????? ?? ??????.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   ? ????? ???? ??? ResourceManager ????? ?????.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TarkovQuestScanner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   ? ??? ??? ??? ???? ???? ?? ??? ??? ?? ?? ???? CurrentUICulture ???
        ///   ??????.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap ??? ???? ???? ????.
        /// </summary>
        internal static System.Drawing.Bitmap title {
            get {
                object obj = ResourceManager.GetObject("title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
